### ISSUE TITLE
Better LFO Attack

### ISSUE THREAD

**Issue by dzannotti** [dzannotti/junox#13]
in this discussion of https://github.com/dzannotti/junox/pull/12#discussion_r283288880
Andy suggested to model the attack as `newValue = (1-oldValue)*rateFactor`
a brief test figured that rateFactor as `phase/attackSamples` meant we wouldn't reach 1.0 within `attackSamples` time, so i deferred it to a later research in order to push the PR along

**Comment by pendragon-andyh** [comment]
The formula I specified never reaches to 1 ... it just gets closer and closer.  Options are:
* Specify a higher number that "1" in the formula - and then stop when we go past 1.  This is the way that most ADSR attacks work.  This technique reduces the "curve" of the formula.
* Leave it as-is, forever getting closer to 1.  This has the advantage of the sound continuing to "evolve" over time (so the sound is less boring to the human ear).

Emulating these synths is not an exact science.  The figures that I provide are at-best approximations that are limited by my ability to accurate measure sub-millisecond events.

**Comment by dzannotti** [comment]
If i multiply the result by 2, it reaches one (just above as it caps at 1.2), given how low impact something like this is, i'd say we keep it like that for now

**Comment by dzannotti** [comment]
This one should have been taken care in #28
