### ISSUE TITLE
Move LPF to synth

### ISSUE THREAD

**Issue by dzannotti** [dzannotti/junox#16]
Juno 60/106 only have 1 VCF not 1 per voice, there's no reason to run 1 per voice currently

**Comment by pendragon-andyh** [comment]
Definitely one VCF for voice.  You hear all sorts of horror stories about the VCF chips failing on the 106, with the result that it is virtually unplayable.

Remember that the envelope and key-follow can modulate the VCF cutoff-frequency ... they are both very much note-specific.

I can confirm that there is only one HPF.

**Comment by dzannotti** [comment]
closing this then
